import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/auth';
import { prisma } from '@/db/prisma';
import { resolveContractorAuth, can, meetsMinTier } from '@/lib/contractor-auth';

/**
 * GET /api/contractor/finance/1099?year=2025&format=csv
 *
 * Returns subcontractor 1099-NEC prep data for the given year.
 * Subcontractors with ≥ $600 in payments are included.
 * format=csv returns a downloadable CSV file.
 */
export async function GET(req: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user?.id) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const contractorAuth = await resolveContractorAuth(session.user.id);
    if (!contractorAuth) return NextResponse.json({ error: 'Not found' }, { status: 404 });
    if (!meetsMinTier(contractorAuth, 'pro')) return NextResponse.json({ error: 'Pro plan required' }, { status: 403 });
    if (!can(contractorAuth, 'financials.view_detailed')) return NextResponse.json({ error: 'Insufficient permissions' }, { status: 403 });

    const { searchParams } = new URL(req.url);
    const year = parseInt(searchParams.get('year') || String(new Date().getFullYear()), 10);
    const format = searchParams.get('format') || 'json';

    const contractorId = contractorAuth.contractorId;
    const start = new Date(year, 0, 1);
    const end = new Date(year, 11, 31, 23, 59, 59);
    const db = prisma as any;

    // Get contractor info for header
    const profile = await prisma.contractorProfile.findUnique({
      where: { id: contractorId },
      select: { businessName: true, email: true, phone: true, baseCity: true, baseState: true },
    });

    // All completed sub assignments in the year
    const assignments = await db.contractorSubcontractorAssignment.findMany({
      where: {
        subcontractor: { contractorId },
        status: { in: ['completed', 'paid'] },
        endDate: { gte: start, lte: end },
      },
      select: {
        agreedPrice: true,
        endDate: true,
        subcontractor: {
          select: {
            id: true,
            companyName: true,
            contactName: true,
            email: true,
            phone: true,
            taxId: true,
            preferredPayment: true,
          },
        },
      },
      orderBy: { endDate: 'asc' },
    });

    // Group by subcontractor
    const subMap: Record<string, {
      id: string;
      companyName: string;
      contactName: string;
      email: string;
      phone: string | null;
      taxId: string | null;
      preferredPayment: string;
      total: number;
      jobCount: number;
      missingTaxId: boolean;
    }> = {};

    for (const a of assignments) {
      const sub = a.subcontractor;
      if (!subMap[sub.id]) {
        subMap[sub.id] = {
          ...sub,
          total: 0,
          jobCount: 0,
          missingTaxId: !sub.taxId,
        };
      }
      subMap[sub.id].total += Number(a.agreedPrice);
      subMap[sub.id].jobCount += 1;
    }

    const all = Object.values(subMap).sort((a, b) => b.total - a.total);
    const requires1099 = all.filter(s => s.total >= 600);
    const below600 = all.filter(s => s.total < 600);
    const missingTaxIds = requires1099.filter(s => s.missingTaxId);

    if (format === 'csv') {
      let csv = `1099-NEC Prep Report — ${year}\n`;
      csv += `Generated by ${profile?.businessName || 'Contractor'} on ${new Date().toLocaleDateString()}\n\n`;
      csv += 'Company Name,Contact Name,Email,Phone,Tax ID (EIN),Total Paid,# Jobs,Needs 1099,Missing Tax ID\n';

      for (const s of all) {
        const needs = s.total >= 600 ? 'Yes' : 'No';
        const missingTax = s.missingTaxId && s.total >= 600 ? 'ACTION REQUIRED' : '';
        csv += `"${s.companyName}","${s.contactName}","${s.email}","${s.phone || ''}","${s.taxId || ''}",${s.total.toFixed(2)},${s.jobCount},${needs},${missingTax}\n`;
      }

      return new NextResponse(csv, {
        status: 200,
        headers: {
          'Content-Type': 'text/csv',
          'Content-Disposition': `attachment; filename="1099-prep-${year}.csv"`,
        },
      });
    }

    return NextResponse.json({
      year,
      contractor: profile,
      summary: {
        totalSubcontractors: all.length,
        requires1099Count: requires1099.length,
        totalAmount1099: requires1099.reduce((s, c) => s + c.total, 0),
        missingTaxIdCount: missingTaxIds.length,
      },
      requires1099,
      below600,
      missingTaxIds,
    });
  } catch (error) {
    console.error('GET /api/contractor/finance/1099', error);
    return NextResponse.json({ error: 'Failed to compute 1099 data' }, { status: 500 });
  }
}
