-- Add new fields to Homeowner table
ALTER TABLE "Homeowner" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "Homeowner" ADD COLUMN IF NOT EXISTS "images" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Homeowner" ADD COLUMN IF NOT EXISTS "yearBuilt" INTEGER;
ALTER TABLE "Homeowner" ADD COLUMN IF NOT EXISTS "squareFootage" INTEGER;
ALTER TABLE "Homeowner" ADD COLUMN IF NOT EXISTS "bedrooms" INTEGER;
ALTER TABLE "Homeowner" ADD COLUMN IF NOT EXISTS "bathrooms" DECIMAL(3,1);
ALTER TABLE "Homeowner" ADD COLUMN IF NOT EXISTS "lotSize" TEXT;
ALTER TABLE "Homeowner" ADD COLUMN IF NOT EXISTS "description" TEXT;
